
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package CargaDatos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Numero = 7;
  public static final int Horario = 13;
  public static final int Usuario = 8;
  public static final int EstudianteUs = 3;
  public static final int Texto = 17;
  public static final int Coma = 5;
  public static final int EOF = 0;
  public static final int Estudiante = 2;
  public static final int Edificio = 10;
  public static final int TextoSin = 18;
  public static final int Curso = 12;
  public static final int Parente_c = 16;
  public static final int Parente_a = 15;
  public static final int error = 1;
  public static final int Catedratico = 9;
  public static final int Colaborador = 4;
  public static final int Salon = 11;
  public static final int Error = 19;
  public static final int PuntoComa = 6;
  public static final int Asignar = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Estudiante",
  "EstudianteUs",
  "Colaborador",
  "Coma",
  "PuntoComa",
  "Numero",
  "Usuario",
  "Catedratico",
  "Edificio",
  "Salon",
  "Curso",
  "Horario",
  "Asignar",
  "Parente_a",
  "Parente_c",
  "Texto",
  "TextoSin",
  "Error"
  };
}

