/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Estructuras.ListaCircular;
import Main.Main;
import static Main.Main.estudiantes;
import static Main.Main.listaCursos;
import Objetos.Asignacion;
import Objetos.Curso;
import Objetos.Estudiante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author meza4
 */
public class ReporteEstudiantesAprobados extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public ReporteEstudiantesAprobados() {
        initComponents();
        setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        semestre = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aprobados = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        reprobados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Usac_logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ver Estudiantes aprobados por semestre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 39, -1, -1));

        user.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        user.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 251, 21));

        tabla.setBackground(new java.awt.Color(255, 255, 204));
        tabla.setForeground(new java.awt.Color(0, 0, 0));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre", "Direccion", "Curso", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 810, 330));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Id:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        id.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        id.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 251, 21));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        tipo.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        tipo.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 251, 21));

        jButton12.setBackground(new java.awt.Color(255, 255, 204));
        jButton12.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("Buscar");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 90, 40));

        semestre.setBackground(new java.awt.Color(255, 255, 204));
        semestre.setForeground(new java.awt.Color(0, 0, 0));
        semestre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(semestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 230, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Semestre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Aprobados:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        aprobados.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        aprobados.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(aprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, 21));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Reprobados:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        reprobados.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        reprobados.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(reprobados, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        user.setText(Main.usuarioActual.getNombre());
        tipo.setText(Main.usuarioActual.getTipo());
        id.setText(String.valueOf(Main.usuarioActual.getId()));

    }//GEN-LAST:event_formComponentShown

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            if (!semestre.getText().equals("")) {
                int contadorAprobados = 0;
                int contadorReprobados = 0;
                ArrayList asignaciones = Main.listaAsignaciones.mostrarAsignaciones();
                DefaultTableModel model = (DefaultTableModel) tabla.getModel();
                model.setRowCount(0);
                for (int i = 0; i < asignaciones.size(); i++) {

                    if (((Asignacion) asignaciones.get(i)).getHorario().getCurso().getSemestre() == Integer.valueOf(semestre.getText())) {
                        if (((Asignacion) asignaciones.get(i)).getNotaFinal() + ((Asignacion) asignaciones.get(i)).getZona() > 61) {
                            contadorAprobados++;
                            model.addRow(new Object[]{((Asignacion) asignaciones.get(i)).getEstudiante().getCarnet(), ((Asignacion) asignaciones.get(i)).getEstudiante().getNombre(), ((Asignacion) asignaciones.get(i)).getEstudiante().getDireccion(), ((Asignacion) asignaciones.get(i)).getHorario().getCurso().getNombre(), "Aprobado"});
                        } else {
                            contadorReprobados++;
                            model.addRow(new Object[]{((Asignacion) asignaciones.get(i)).getEstudiante().getCarnet(), ((Asignacion) asignaciones.get(i)).getEstudiante().getNombre(), ((Asignacion) asignaciones.get(i)).getEstudiante().getDireccion(), ((Asignacion) asignaciones.get(i)).getHorario().getCurso().getNombre(), "Reprobado"});

                        }

                    }

                }
                aprobados.setText(String.valueOf(contadorAprobados));
                reprobados.setText(String.valueOf(contadorReprobados));
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un semestre");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteEstudiantesAprobados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteEstudiantesAprobados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteEstudiantesAprobados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteEstudiantesAprobados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteEstudiantesAprobados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aprobados;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reprobados;
    private javax.swing.JFormattedTextField semestre;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
